[[about]]
== About

[[what-is-datasource-proxy]]
=== What is datasource-proxy?

datasource-proxy provides simple API to intercept JDBC interactions and allows user to perform own logic
before/after query or method executions. +
With built-in interceptors, it supports query logging, slow query detection, query
statistics, interaction tracing, and more out of the box, as well as adding your own interceptors.


[[feature]]
=== Feature

Query and Parameter Logging::
+
You can log executing database queries and parameters with choice of your logging framework(commons, slf4j,
java util logging, sysout, or your own).
Output can be formatted as JSON.


Slow Query Detector and Loggers::
+
You can add callbacks for slow queries that take longer than threshold time you specified.
Slow query loggers are available out of the box.

Connection ID::
+
Each connection is assigned unique ID that is a sequentially increasing number in default implementation.
The connection ID is included in logging entry.

Query Metrics::
+
You can collect statistics of executed query such as total time, number of select, insert, update, delete queries, etc.
Output can be formatted as JSON.

Custom Logic Injection for Query Execution::
+
You can write own `QueryExecutionListener` and they can get called before/after query execution.

Web Application Support::
+
`ProxyDataSource` can be configured via JNDI.
Query metrics information are available per web request basis(request-response lifecycle).
For UI with JSP, custom tag to access metrics(`<dsp:metrics/>`) is available as well.

Query and parameter replacement::
+
`QueryTransformer` and `ParameterTransformer` allows you to modify executing query and parameters right before
calling the database.


=== Example Log


Query execution (single line):

```
Name:MyProxy, Connection:1, Time:1, Success:True, Type:Statement, Batch:False, QuerySize:1, BatchSize:0, Query:["CREATE TABLE users(id INT, name VARCHAR(255))"], Params:[]
Name:MyProxy, Connection:2, Time:5, Success:True, Type:Prepared, Batch:True, QuerySize:1, BatchSize:2, Query:["INSERT INTO users (id, name) VALUES (?, ?)"], Params:[(1,foo),(2,bar)]
```

Query execution (multiple lines):

```
Name:MyProxy, Connection:1, Time:3, Success:True
Type:Callable, Batch:True, QuerySize:1, BatchSize:2
Query:["{call getEmployer (?, ?)}"]
Params:[(id=100,name=foo),(id=200,name=bar)]
```

JSON output:

```json
{"name":"MyProxy", "connection":1, "time":1, "success":true, "type":"Statement", "batch":false, "querySize":1, "batchSize":0, "query":["CREATE TABLE users(id INT, name VARCHAR(255))"], "params":[]}
{"name":"MyProxy", "connection":2, "time":0, "success":true, "type":"Prepared", "batch":true, "querySize":1, "batchSize":3, "query":["INSERT INTO users (id, name) VALUES (?, ?)"], "params":[["1","foo"],["2","bar"],[3","baz"]]}
```

Query metrics:

```
Name:"MyProxy", Time:6, Total:1, Success:1, Failure:0, Select:1, Insert:0, Update:0, Delete:0, Other:0
```

```json
// JSON output
{"name":"MyProxy", "time":10, "total":3, "success":3, "failure":0, "select":1, "insert":2, "update":0, "delete":0, "other":0}
```
