[[about]]
== About

[[what-is-datasource-proxy]]
=== What is datasource-proxy?

datasource-proxy provides a simple API for intercepting JDBC interactions and lets you add your own logic
before or after query execution or method calls. +
The proxy works as a `javax.sql.DataSource` and takes listeners.
Predefined listeners support query logging, slow query detection, query execution statistics, interaction
tracing, and more. You can also easily add custom listeners to the listener chain.


[[built-in-support]]
=== Built-in Support

Query and Parameter Logging::
+
You can log executed database queries and parameters using your preferred logging framework (Commons Logging,
SLF4J, Java Util Logging, System.out, or your own implementation).
The output can be formatted as JSON.


Slow Query Detection and Logging::
+
You can register callbacks for queries that exceed a configured threshold.
Slow query loggers are available out of the box.


Connection ID::
+
Each connection is assigned a unique ID, implemented as a sequentially increasing number by default.
The connection ID is included in the log entry.


Query Metrics::
+
You can collect statistics for executed queries, such as total time and the number of `SELECT`, `INSERT`,
`UPDATE`, and `DELETE` statements.
The output can be formatted as JSON.


Custom Logic Injection for Query and Method Execution::
+
You can write your own `QueryExecutionListener` implementations and have them invoked before or after
query execution.
`MethodExecutionListener` is also invoked for each JDBC API interaction.


Web Application Support::
+
`ProxyDataSource` can be configured via JNDI.
Query metrics are available on a per-web-request basis (request-response lifecycle).
For JSP-based UIs, a custom tag for accessing metrics (`<dsp:metrics/>`) is also available.


Query and Parameter Replacement::
+
`QueryTransformer` and `ParameterTransformer` allow you to modify the executing query and parameters just
before they are sent to the database.


Method Tracing::
+
Intercept JDBC API interactions such as obtaining a connection, creating prepared statements, setting
parameters, and executing queries.


=== Jakarta Namespace

The `javax.sql.*` classes are part of the Java SE APIs, so they are not affected by the namespace change in
Java EE APIs to Jakarta. For example, the `javax.sql.DataSource` class remains in the `javax.sql` package.

In datasource-proxy, there are a few usages of the `javax` namespace in JNDI and query count support via
`ServletRequestListener`.
These are not used frequently and are expected to be removed or separated in the next major version release.

If you require these features in the Jakarta namespace, it is recommended that you create your own classes
based on the existing implementations.


=== Sample Log Output


Query execution (single line):

```
Name:MyProxy, Connection:1, Time:1, Success:True, Type:Statement, Batch:False, QuerySize:1, BatchSize:0, Query:["CREATE TABLE users(id INT, name VARCHAR(255))"], Params:[]
Name:MyProxy, Connection:2, Time:5, Success:True, Type:Prepared, Batch:True, QuerySize:1, BatchSize:2, Query:["INSERT INTO users (id, name) VALUES (?, ?)"], Params:[(1,foo),(2,bar)]
```

Query execution (multiple lines):

```
Name:MyProxy, Connection:1, Time:3, Success:True
Type:Callable, Batch:True, QuerySize:1, BatchSize:2
Query:["{call getEmployer (?, ?)}"]
Params:[(id=100,name=foo),(id=200,name=bar)]
```

JSON output:

```json
{"name":"MyProxy", "connection":1, "time":1, "success":true, "type":"Statement", "batch":false, "querySize":1, "batchSize":0, "query":["CREATE TABLE users(id INT, name VARCHAR(255))"], "params":[]}
{"name":"MyProxy", "connection":2, "time":0, "success":true, "type":"Prepared", "batch":true, "querySize":1, "batchSize":3, "query":["INSERT INTO users (id, name) VALUES (?, ?)"], "params":[["1","foo"],["2","bar"],["3","baz"]]}
```

Query metrics:

```
Name:"MyProxy", Time:6, Total:1, Success:1, Failure:0, Select:1, Insert:0, Update:0, Delete:0, Other:0
```

```json
// JSON output
{"name":"MyProxy", "time":10, "total":3, "success":3, "failure":0, "select":1, "insert":2, "update":0, "delete":0, "other":0}
```

Method tracing:

.Output:
```
[1][success][0ms][conn=1] ProxyDataSource#getConnection()
[2][success][1ms][conn=1] JDBCConnection#prepareStatement("INSERT INTO users (id, name) VALUES (?, ?)")
[3][success][0ms][conn=1] JDBCPreparedStatement#setString(2,"FOO")
[4][success][0ms][conn=1] JDBCPreparedStatement#setInt(1,100)
[5][success][0ms][conn=1] JDBCPreparedStatement#addBatch()
[6][success][0ms][conn=1] JDBCPreparedStatement#setInt(1,200)
[7][success][0ms][conn=1] JDBCPreparedStatement#setString(2,"BAR")
[8][success][0ms][conn=1] JDBCPreparedStatement#addBatch()
[9][success][1ms][conn=1] JDBCPreparedStatement#executeBatch()
[10][success][0ms][conn=1] JDBCPreparedStatement#close()
[11][success][0ms][conn=1] JDBCConnection#close()
```

