[[built-in-listeners]]
== Built-in Listeners

[[query-logging-listener]]
=== Query Logging Listener

The query logging listener is the most commonly used listener. It logs executed queries and their actual
parameters to Commons Logging, SLF4J, JUL, or `System.out`.

*Sample output*

```
Name:MyProxy, Connection:1, Time:1, Success:True, Type:Statement, Batch:False, QuerySize:1, BatchSize:0, Query:["CREATE TABLE users(id INT, name VARCHAR(255))"], Params:[]
Name:MyProxy, Connection:2, Time:5, Success:True, Type:Prepared, Batch:True, QuerySize:1, BatchSize:2, Query:["INSERT INTO users (id, name) VALUES (?, ?)"], Params:[(1,foo),(2,bar)]
```

[cols="20,80"]
|===
| Key           | Value

| Name          | Name of `ProxyDataSource`
| Connection    | Connection ID
| Time          | How long the query took to execute, in milliseconds
| Success       | Whether the query execution succeeded
| Type          | Type of statement (_Statement/Prepared/Callable_)
| Batch         | Batch execution
| QuerySize     | Number of queries
| BatchSize     | Number of batch operations
| Query         | The query text
| Params        | Query parameters
|===


`ProxyDataSourceBuilder` provides methods for easily configuring and registering these listeners.

```java
builder
  .logQueryByCommons()   // log using Commons Logging
  .logQueryBySlf4j()     // log using SLF4J
  .logQueryByJUL()       // log using Java Util Logging
  .logQueryToSysOut()    // log using System.out

  .multiline()           // enable multiline output
  .build();
```

NOTE: If you choose to use Commons Logging or SLF4J, add the corresponding dependency to your project.

By default, each log entry is printed on a single line. If the `multiline()` option is set, the log is written
across multiple lines. Likewise, the `json()` option prints the output in JSON format.


Here is another example of a multiline log that formats the query using Hibernate formatting.

Datasource-proxy v1.9 added the `formatQuery()` method on `ProxyDataSourceBuilder`, which lets you specify a
callback to modify the query before logging.

```java
// v1.9 or above
Formatter formatter = FormatStyle.BASIC.getFormatter();
DataSource ds = ProxyDataSourceBuilder
                  .create(actualDataSource)
                  .formatQuery(formatter::format)
                  .multiline()
                  .logQueryToSysOut()
                  .build()
```

[source,java]
----
// prior to v1.9
QueryLogEntryCreator logEntryCreator = new DefaultQueryLogEntryCreator() {
  @Override
  protected String formatQuery(String query) {
    return FormatStyle.BASIC.getFormatter().format(query);  // use Hibernate formatter
  }
};

logEntryCreator.setMultiline(true);  // enable multiline output

// print to System.out
SystemOutQueryLoggingListener listener = new SystemOutQueryLoggingListener();
listener.setQueryLogEntryCreator(logEntryCreator);

return ProxyDataSourceBuilder
            .create(actualDataSource)
            .listener(listener)
            .build()
----

You can also filter which queries are logged by providing a `LoggingFilter`:

[source,java]
----
builder
  .logQueryBySlf4j()
  // Only log queries that are not sent to the 'audit' table
  .loggingFilter((execInfo, queryInfoList) ->
    queryInfoList.stream().noneMatch(q -> q.getQuery().contains("audit"))
  )
----

If no filter is set, all queries are logged by default.

=== Slow Query Logging Listener

There are two approaches to detecting slow queries:

During execution::
Detect slow queries *while* they are running.
A scheduled check fires once the query has run longer than the configured threshold, even if the query has not
finished yet. `SlowQueryListener` uses this approach.
This approach is sometimes called _preemptive_; however, it only notifies you about the query.
The running query is NOT interrupted or canceled.

After execution::
Detect slow queries *after* they have finished.
The `afterQuery` callback compares the query's elapsed time with the threshold.
This is a simple approach that can be implemented with any `QueryExecutionListener`.
This approach is sometimes called _non-preemptive_.

[cols="1,2,2", options="header"]
|===
|
|During execution (`SlowQueryListener`)
|After execution (`afterQuery` callback)

|When it is triggered
|When the threshold has passed while the query is still running
|After the query has finished

|Elapsed time in `ExecutionInfo`
|Time at the moment of the check (approximately the threshold time)
|Actual query execution time

|Query result, success/failure
|Not available
|Available

|Thread that runs the callback
|Thread of the scheduled executor in `SlowQueryListener`
|Thread that executed the query

|Queries that hang or never return
|Detected
|Not detected

|Overhead
|Schedules a check for each query execution
|Compares elapsed time
|===

Both approaches can be used together.
For example, use `SlowQueryListener` to get an early notice of long-running queries and use an
`afterQuery` callback to record their actual execution time.

[[slow-query-during-execution]]
==== During execution

When a query takes longer than the configured threshold, `SlowQueryListener` invokes a callback method.
The callback is invoked only once for the target query if it exceeds the threshold time.

Combining logging and slow query detection, the following built-in classes write slow query entries to their
corresponding loggers:

- `CommonsSlowQueryListener`
- `SLF4JSlowQueryListener`
- `JULSlowQueryListener`
- `SystemOutSlowQueryListener`


`ProxyDataSourceBuilder` provides methods for configuring these listeners.

```java
builder
  .logSlowQueryByCommons(1, TimeUnit.SECONDS)   // log slow queries using Commons Logging
  .logSlowQueryBySlf4j(1, TimeUnit.SECONDS)     // log slow queries using SLF4J
  .logSlowQueryByJUL(1, TimeUnit.SECONDS)       // log slow queries using Java Util Logging
  .logSlowQueryToSysOut(1, TimeUnit.SECONDS)    // log slow queries using System.out

  .multiline()           // enable multiline output
  .build();
```

[NOTE]
.Elapsed Time
====
`SlowQueryListener` triggers its callback when query execution exceeds the configured threshold.

For example, if the threshold is set to 1 minute and a query takes 5 minutes to complete, the query is logged
when 1 minute has passed while the query is still running. +
This is expected behavior. Because the query is still executing, the elapsed time in `ExecutionInfo` is the time
at the moment of the check (about 1 minute in this example), not the actual execution time of the query (5 minutes).

To log slow queries with their actual execution time, use the <<slow-query-after-execution, after execution>>
approach.
====

[[slow-query-after-execution]]
==== After execution

To log queries that exceeded the threshold with their actual execution time, you can customize the existing
<<query-logging-listener>> implementation instead of using `SlowQueryListener`.

Here is a sample implementation using `SLF4JQueryLoggingListener`:

```java
long thresholdInMills = ...
SLF4JQueryLoggingListener listener = new SLF4JQueryLoggingListener() {
  @Override
  public void afterQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList) {
    // call query logging logic only when it took more than the threshold
    if (thresholdInMills <= execInfo.getElapsedTime()) {
      super.afterQuery(execInfo, queryInfoList);
    }
  }
};

listener.setLogLevel(SLF4JLogLevel.WARN);
```

This implementation logs queries that took longer than the configured threshold _AFTER_ the query execution
has finished, so the actual query execution time is available.

To perform other actions for slow queries, such as recording metrics or sending notifications, register an
`afterQuery` callback with `ProxyDataSourceBuilder`:

```java
long thresholdInMills = ...
builder
  .afterQuery((execInfo, queryInfoList) -> {
    if (thresholdInMills <= execInfo.getElapsedTime()) {
      // slow query: log, record metrics, send notification, etc.
    }
  })
  .build();
```


=== Query Count Listener


`DataSourceQueryCountListener` collects statistics for executed queries, such as the number of query types
(`SELECT`, `INSERT`, `UPDATE`, `DELETE`), statement types (`Statement`, `Prepared`, `Callable`), and more.
This class also accepts a strategy for storing such metrics. The default strategy stores metrics in a
thread-local value, which is expected to be reset at the end of the request-response lifecycle.
Another strategy is `SingleQueryCountHolder`, which accumulates query metrics from all threads until the metrics
are explicitly cleared.


```java
builder.
  .countQuery()    // enable collecting query metrics
//  .countQuery(new SingleQueryCountHolder())  // enable and specify a query count holder
  .build();
```

Stored metrics can be retrieved by the following static method.

```java
QueryCountHolder.get()
```

NOTE: Semantics changes based on how metrics are stored - thread local vs global map.
When thread local is chosen, you need to clean up the stored metrics at the end of request-response lifecycle.
You can call `QueryCountHolder.clear()` explicitly. Or, if built-in query-count-logging-listeners(will be
addressed below) are registered, they automatically call `clear()` after it logs the count stats.


Combination of count listener and logging, datasource-proxy has built-in support for logging current query count
metrics to loggers(commons, slf4j, jul, or system.out).
They are available in servlet `Filter` and `ServletRequestListener` implementation.
Furthermore, there is a custom tag for jsp.


==== Query count logging with servlet Filter

- CommonsQueryCountLoggingServletFilter
- JULQueryCountLoggingServletFilter
- SLF4JQueryCountLoggingServletFilter
- SystemOutQueryCountLoggingServletFilter

`QueryCountLoggerBuilder` class helps constructing filter instance.

.with `web.xml`:
```xml
<filter>
  <filter-name>queryCountFilter</filter-name>
  <filter-class>net.ttddyy.dsproxy.support.CommonsQueryCountLoggingServletFilter</filter-class>
  <init-param>  <!-- OPTIONAL -->
    <param-name>clearQueryCounter</param-name>
    <param-value>true</param-value>
  </init-param>
  <init-param>  <!-- OPTIONAL -->
    <param-name>logLevel</param-name>
    <param-value>INFO</param-value>
  </init-param>
</filter>
```

==== Query count logging with ServletRequestListener

- CommonsQueryCountLoggingRequestListener
- JULQueryCountLoggingRequestListener
- SLF4JQueryCountLoggingRequestListener
- SystemOutQueryCountLoggingRequestListener
- QueryCounterClearServletRequestListener

.with `web.xml`:
```xml
<context-param>  <!-- OPTIONAL -->
  <param-name>queryCountCommonsLogLevel</param-name>
  <param-value>INFO</param-value>
</context-param>

<listener>
  <listener-class>net.ttddyy.dsproxy.support.CommonsQueryCountLoggingRequestListener</listener-class>
</listener>
```

==== Taglib Support

For jsp, a custom tag is supported to display query count metrics.

Declare custom tag:

```jsp
<%@ taglib prefix="dsp" uri="http://www.ttddyy.net/dsproxy/tags" %>
```

When datasource is not specfied, total number of each datasource will be displayed.

```jsp
<dsp:metrics metric="select"/>
<dsp:metrics metric="update"/>
<dsp:metrics metric="insert"/>
<dsp:metrics metric="delete"/>
<dsp:metrics metric="other"/>
<dsp:metrics metric="total"/>
<dsp:metrics metric="call"/>
<dsp:metrics metric="failure"/>
<dsp:metrics metric="time"/>
```


Specific datasource

```jsp
<dsp:metrics metric="select" dataSource="FOO"/>
<dsp:metrics metric="update" dataSource="FOO"/>
<dsp:metrics metric="insert" dataSource="FOO"/>
<dsp:metrics metric="delete" dataSource="FOO"/>
<dsp:metrics metric="other" dataSource="FOO"/>
<dsp:metrics metric="total" dataSource="FOO"/>
<dsp:metrics metric="call" dataSource="FOO"/>
<dsp:metrics metric="failure" dataSource="FOO"/>
<dsp:metrics metric="time" dataSource="FOO"/>
```

.metric attribute
[cols="20,80"]
|===
| Name           | Description

| select         | Num of select queries
| insert         | Num of insert queries
| update         | Num of update queries
| delete         | Num of delete queries
| other          | Num of other queries
| statement      | Total num of statements
| prepared       | Total num of prepared statements
| callable       | Total num of callable statements
| total          | Total num of queries
| success        | Num of success queries
| failure        | Num of failure queries
| time           | Query execution time
|===


[[tracing-method-listener]]
=== Tracing Method Listener

`TracingMethodListener` is a method execution listener that prints out all JDBC API interaction.


Sample JDBC interaction using HSQL:

.Code:
```java
Connection conn = dataSource.getConnection()
PreparedStatement ps = conn.prepareStatement("INSERT INTO users (id, name) VALUES (?, ?)");
ps.setString(2, "FOO");
ps.setInt(1, 100);
ps.addBatch();
ps.setInt(1, 200);
ps.setString(2, "BAR");
ps.addBatch();
ps.executeBatch();
ps.close();
conn.close();
```

.Output:
```
[1][success][0ms][conn=1] ProxyDataSource#getConnection()
[2][success][1ms][conn=1] JDBCConnection#prepareStatement("INSERT INTO users (id, name) VALUES (?, ?)")
[3][success][0ms][conn=1] JDBCPreparedStatement#setString(2,"FOO")
[4][success][0ms][conn=1] JDBCPreparedStatement#setInt(1,100)
[5][success][0ms][conn=1] JDBCPreparedStatement#addBatch()
[6][success][0ms][conn=1] JDBCPreparedStatement#setInt(1,200)
[7][success][0ms][conn=1] JDBCPreparedStatement#setString(2,"BAR")
[8][success][0ms][conn=1] JDBCPreparedStatement#addBatch()
[9][success][1ms][conn=1] JDBCPreparedStatement#executeBatch()
[10][success][0ms][conn=1] JDBCPreparedStatement#close()
[11][success][0ms][conn=1] JDBCConnection#close()
```

`ProxyDataSourceBuilder` provides following methods:


```java
builder
  .traceMethods()
  .build();
```

To change output, the builder method also takes a string consumer.

```java
builder
  // change the output to logger
  .traceMethods(message -> logger.debug(message))
  .build();
```

`traceMethodsWhen` method takes a boolean supplier to dynamically turn on/off tracing.

```java
builder
  .traceMethodsWhen(() -> ...condition to perform tracing... )
  .build();
```


[[custom-listeners]]
=== Custom Listeners

When you create a custom listener, you can register it via `listener()` or `methodListener()` methods.

```java
  builder
      .listener(myQueryListener)          // register QueryExecutionListener
      .methodListener(myMethodListener)   // register MethodExecutionListener
      .build();
```


Also, with Java8 lambda, builder provides simple methods to inline listener definitions.

- `beforeQuery()` and `afterQuery()` to register `QueryExecutionListener`
- `beforeMethod()` and `afterMethod()` to register `MethodExecutionListener`


```java
  builder
      // register MethodExecutionListener
      .afterMethod(executionContext -> {
        ....
      })
      // register QueryExecutionListener
      .afterQuery((execInfo, queryInfoList) -> {
          ...
      })

```

