[[built-in-listeners]]
== Built-in Listeners

[[query-logging-listener]]
=== Query Logging Listener

Query logging listener is the most used listener that logs executing query with actual parameters
to commons/slf4j/JUL logger or System.out.

*Sample output*

```
Name:MyProxy, Connection:1, Time:1, Success:True, Type:Statement, Batch:False, QuerySize:1, BatchSize:0, Query:["CREATE TABLE users(id INT, name VARCHAR(255))"], Params:[]
Name:MyProxy, Connection:2, Time:5, Success:True, Type:Prepared, Batch:True, QuerySize:1, BatchSize:2, Query:["INSERT INTO users (id, name) VALUES (?, ?)"], Params:[(1,foo),(2,bar)]
```

[cols="20,80"]
|===
| Key           | Value

| Name          | Name of `ProxyDataSource`
| Connection    | Connection ID
| Time          | How long query took to execute in ms.
| Success       | Query execution was successful or not.
| Type          | Type of statement (_Statement/Prepared/Callable_).
| Batch         | Batch execution.
| QuerySize     | Number of queries.
| BatchSize     | Number of batch.
| Query         | Query
| Params        | Query parameters
|===


`ProxyDataSourceBuilder` provides methods to easily configure and register these listeners.

```java
builder
  .logQueryByCommons()   // log using Commons
  .logQueryBySlf4j()     // log using SLF4J
  .logQueryByJUL()       // log using Java Util Logging
  .logQueryToSysOut()    // log using System.out

  .multiline()           // enable multiline output
  .build();
```

NOTE: If you choose to use commons or slf4j loggers, you need to add dependency to your project accordingly.

By default, each log entry is printed to single line. If `multiline()` option is set, it prints out
a log over multiple lines. Also, `json()` option prints out log in json format.


Here is another example printing multiline log with formatting query with formatter from Hibernate.


```java
    QueryLogEntryCreator logEntryCreator = new DefaultQueryLogEntryCreator() {
        @Override
        protected String formatQuery(String query) {
            return FormatStyle.BASIC.getFormatter().format(query);  // use Hibernte formatter
        }
    };
    creator.setMultiline(true);  // enable multiline output

    // print out to system.out
    SystemOutQueryLoggingListener listener = new SystemOutQueryLoggingListener();
    listener.setQueryLogEntryCreator(creator);

    return ProxyDataSourceBuilder
                .create(actualDataSource)
                .listener(listener)
                .build()
```

=== Slow Query Logging Listener

When query takes more than specified threshold, `SlowQueryListener` executes a callback method.
The callback is invoked only once for the target query if it exceeds the threshold time.

Combining logging and slow query detection, following built-in classes writes out slow query
to its corresponding logger.

- `CommonsSlowQueryListener`
- `SLF4JSlowQueryListener`
- `JULSlowQueryListener`
- `SystemOutSlowQueryListener`


`ProxyDataSourceBuilder` provides methods to configure those listeners.

```java
builder
  .logSlowQueryByCommons(1, TimeUnit.SECONDS)   // log slow query using Commons
  .logSlowQueryBySlf4j(1, TimeUnit.SECONDS)     // log slow query using Slf4J
  .logSlowQueryByJUL(1, TimeUnit.SECONDS)       // log slow query using Java Util Logging
  .logSlowQueryToSysOut(1, TimeUnit.SECONDS)    // log slow query using System.out

  .multiline()           // enable multiline output
  .build();
```

[NOTE]
.Elapsed Time
====
`SlowQueryListener` triggers callback when query execution exceeds specified threshold time.

For example, when 1 min is set to the threshold in a slow query logging listener and a query takes 5 min to run,
it will log the query when 1 min has passed while the query is still running. +
This is expected behavior; however, elapsed time in ExecutionInfo is not populated because it is still executing
the query.

To log queries that have passed threshold with elapsed time populated, you can customize existing
<<query-logging-listener>> instead of `SlowQueryListener`.

Here is sample implementation with SLF4JQueryLoggingListener:

```java
long thresholdInMills = ...
SLF4JQueryLoggingListener listener = new SLF4JQueryLoggingListener() {
  @Override
  public void afterQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList) {
    // call query logging logic only when it took more than threshold
    if (thresholdInMills <= execInfo.getElapsedTime()) {
      super.afterQuery(execInfo, queryInfoList);
    }
  }
};

listener.setLogLevel(SLF4JLogLevel.WARN);
```

This implementation will log queries that took longer than specified threshold _AFTER_ query execution has finished.
So that, query execution time is populated.

====


=== Query Count Listener


`DataSourceQueryCountListener` collects statistics of executed queries, such as number of query types(select, insert,
update, delete), statement types(statement, prepared, callable), etc.
This class also takes strategy to store such metrics. Default strategy stores metrics in thread-local expecting
metrics get reset at the end of the request-response lifecycle.
Another strategy is `SingleQueryCountHolder`. This accumulates query metrics from all threads until explicitly
clear the metrics.


```java
builder.
  .countQuery()    // enable collecting query metrics
//  .countQuery(new SingleQueryCountHolder())  // enable and specify query count holder
  .build();
```

Stored metrics can be retrieved by following static method.

```java
QueryCountHolder.get()
```

NOTE: Semantics changes based on how metrics are stored - thread local vs global map.
When thread local is chosen, you need to clean up the stored metrics at the end of request-response lifecycle.
You can call `QueryCountHolder.clear()` explicitly. Or, if built-in query-count-logging-listeners(will be
addressed below) are registered, they automatically call `clear()` after it logs the count stats.


Combination of count listener and logging, datasource-proxy has built-in support for logging current query count
metrics to loggers(commons, slf4j, jul, or system.out).
They are available in servlet `Filter` and `ServletRequestListener` implementation.
Furthermore, there is a custom tag for jsp.


==== Query count logging with servlet Filter

- CommonsQueryCountLoggingServletFilter
- JULQueryCountLoggingServletFilter
- SLF4JQueryCountLoggingServletFilter
- SystemOutQueryCountLoggingServletFilter

`QueryCountLoggerBuilder` class helps constructing filter instance.

.with `web.xml`:
```xml
<filter>
  <filter-name>queryCountFilter</filter-name>
  <filter-class>net.ttddyy.dsproxy.support.CommonsQueryCountLoggingServletFilter</filter-class>
  <init-param>  <!-- OPTIONAL -->
    <param-name>clearQueryCounter</param-name>
    <param-value>true</param-value>
  </init-param>
  <init-param>  <!-- OPTIONAL -->
    <param-name>logLevel</param-name>
    <param-value>INFO</param-value>
  </init-param>
</filter>
```

==== Query count logging with ServletRequestListener

- CommonsQueryCountLoggingRequestListener
- JULQueryCountLoggingRequestListener
- SLF4JQueryCountLoggingRequestListener
- SystemOutQueryCountLoggingRequestListener
- QueryCounterClearServletRequestListener

.with `web.xml`:
```xml
<context-param>  <!-- OPTIONAL -->
  <param-name>queryCountCommonsLogLevel</param-name>
  <param-value>INFO</param-value>
</context-param>

<listener>
  <listener-class>net.ttddyy.dsproxy.support.CommonsQueryCountLoggingRequestListener</listener-class>
</listener>
```

==== Taglib Support

For jsp, a custom tag is supported to display query count metrics.

Declare custom tag:

```jsp
<%@ taglib prefix="dsp" uri="http://www.ttddyy.net/dsproxy/tags" %>
```

When datasource is not specfied, total number of each datasource will be displayed.

```jsp
<dsp:metrics metric="select"/>
<dsp:metrics metric="update"/>
<dsp:metrics metric="insert"/>
<dsp:metrics metric="delete"/>
<dsp:metrics metric="other"/>
<dsp:metrics metric="total"/>
<dsp:metrics metric="call"/>
<dsp:metrics metric="failure"/>
<dsp:metrics metric="time"/>
```


Specific datasource

```jsp
<dsp:metrics metric="select" dataSource="FOO"/>
<dsp:metrics metric="update" dataSource="FOO"/>
<dsp:metrics metric="insert" dataSource="FOO"/>
<dsp:metrics metric="delete" dataSource="FOO"/>
<dsp:metrics metric="other" dataSource="FOO"/>
<dsp:metrics metric="total" dataSource="FOO"/>
<dsp:metrics metric="call" dataSource="FOO"/>
<dsp:metrics metric="failure" dataSource="FOO"/>
<dsp:metrics metric="time" dataSource="FOO"/>
```

.metric attribute
[cols="20,80"]
|===
| Name           | Description

| select         | Num of select queries
| insert         | Num of insert queries
| update         | Num of update queries
| delete         | Num of delete queries
| other          | Num of other queries
| statement      | Total num of statements
| prepared       | Total num of prepared statements
| callable       | Total num of callable statements
| total          | Total num of queries
| success        | Num of success queries
| failure        | Num of failure queries
| time           | Query execution time
|===


[[tracing-method-listener]]
=== Tracing Method Listener

`TracingMethodListener` is a method execution listener that prints out all JDBC API interaction.


Sample JDBC interaction using HSQL:

.Code:
```java
Connection conn = dataSource.getConnection()
PreparedStatement ps = conn.prepareStatement("INSERT INTO users (id, name) VALUES (?, ?)");
ps.setString(2, "FOO");
ps.setInt(1, 100);
ps.addBatch();
ps.setInt(1, 200);
ps.setString(2, "BAR");
ps.addBatch();
ps.executeBatch();
ps.close();
conn.close();
```

.Output:
```
[1][success][0ms][conn=1] ProxyDataSource#getConnection()
[2][success][1ms][conn=1] JDBCConnection#prepareStatement("INSERT INTO users (id, name) VALUES (?, ?)")
[3][success][0ms][conn=1] JDBCPreparedStatement#setString(2,"FOO")
[4][success][0ms][conn=1] JDBCPreparedStatement#setInt(1,100)
[5][success][0ms][conn=1] JDBCPreparedStatement#addBatch()
[6][success][0ms][conn=1] JDBCPreparedStatement#setInt(1,200)
[7][success][0ms][conn=1] JDBCPreparedStatement#setString(2,"BAR")
[8][success][0ms][conn=1] JDBCPreparedStatement#addBatch()
[9][success][1ms][conn=1] JDBCPreparedStatement#executeBatch()
[10][success][0ms][conn=1] JDBCPreparedStatement#close()
[11][success][0ms][conn=1] JDBCConnection#close()
```

`ProxyDataSourceBuilder` provides following methods:


```java
builder
  .traceMethods()
  .build();
```

To change output, the builder method also takes a string consumer.

```java
builder
  // change the output to logger
  .traceMethods(message -> logger.debug(message))
  .build();
```

`traceMethodsWhen` method takes a boolean supplier to dynamically turn on/off tracing.

```java
builder
  .traceMethodsWhen(() -> ...condition to perform tracing... )
  .build();
```


[[custom-listeners]]
=== Custom Listeners

When you create a custom listener, you can register it via `listener()` or `methodListener()` methods.

```java
  builder
      .listener(myQueryListener)          // register QueryExecutionListener
      .methodListener(myMethodListener)   // register MethodExecutionListener
      .build();
```


Also, with Java8 lambda, builder provides simple methods to inline listener definitions.

- `beforeQuery()` and `afterQuery()` to register `QueryExecutionListener`
- `beforeMethod()` and `afterMethod()` to register `MethodExecutionListener`


```java
  builder
      // register MethodExecutionListener
      .afterMethod(executionContext -> {
        ....
      })
      // register QueryExecutionListener
      .afterQuery((execInfo, queryInfoList) -> {
          ...
      })

```

