[[changelog-1.3.3]]
=== 1.3.3
* update `DefaultQueryLogEntryCreator` to allow subclasses to override log entry details


[[changelog-1.3.2]]
=== 1.3.2

* add `CommonsOracleOutputParameterLoggingListener`
* add new listener for oracle to log output params. `CommonsOracleOutputParameterLoggingListener`


[[changelog-1.3.1]]
=== 1.3.1

* make logger name configurable in `CommonsQueryLoggingListener` and `SLF4JQueryLoggingListener`
* `setNull` and `registerOutParameter` receives descriptive string value in `QueryInfo#getQueryArgsList` (temporal implementation)
* `ExecutionInfo` will have access to the statement/prepared/callable object used by the execution


[[changelog-1.3]]
=== 1.3

* update minimum jdk to java6+
* add java8 new jdbc API (JDBC 4.2)
* new JNDI support class: `ProxyDataSourceObjectFactory`
* new fluent API builder: `ProxyDataSourceBuilder`

* logging:
** update log format
** add json format
** more entries:  statement-type, batch, batch-size
** new logger for System.Out

* change metric names:
call => total, elapsedTime => time, added success, failure, etc.

* rename `~QueryCountLoggingFilter` to `~QueryCountServletFilter`
* remove deprecated methods


