[[changelog-1.4.6]]
=== 1.4.6

* Method and parameter replacement in `MethodExecutionListener`.  +
  See details on <<replace-invoking-method-and-parameters>>.

* Updated <<auto-retrieve-generated-keys>> feature. Auto-retrieval is now only called when key-generation is specified.  +
  Following methods specify key-generation:
  - `Connection#prepareStatement(String, int[])`
  - `Connection#prepareStatement(String, String[])`
  - `Statement#execute(String, int[])`
  - `Statement#execute(String, String[])`
  - `Statement#executeUpdate(String, int[])`
  - `Statement#executeUpdate(String, String[])`
  - `Statement#executeLargeUpdate(String, int)`
  - `Statement#executeLargeUpdate(String, int[])`
  - `Statement#executeLargeUpdate(String, String[])`

* Make <<auto-retrieve-generated-keys-for-batch,generated-keys auto-retrieval for batch execution>> configurable.
** `ProxyDataSourceBuilder#retrieveGeneratedKeysForBatch`
***  batch execution for `Statement`: auto-retrieval is set to `false` to default
***  batch execution for `Prepared/Callable`: auto-retrieval is set to `true` to default