[[changelog-1.4.6]]
=== 1.4.6

* Executing target method and parameter replacement in `MethodExecutionListener`.
  See details on <<replace-invoking-method-and-parameters>>.

* Update <<auto-retrieve-generated-keys>> to be called only when key-generation is specified.
  - `Connection#prepareStatement(String)`
  - `Connection#prepareStatement(String, int[])`
  - `Connection#prepareStatement(String, String[])`
  - `Statement#execute(String)`
  - `Statement#execute(String, int[])`
  - `Statement#execute(String, String[])`
  - `Statement#executeUpdate(String)`
  - `Statement#executeUpdate(String, int[])`
  - `Statement#executeUpdate(String, String[])`
  - `Statement#executeLargeUpdate(String, int)`
  - `Statement#executeLargeUpdate(String, int[])`
  - `Statement#executeLargeUpdate(String, String[])`

* Make <<auto-retrieve-generated-keys-for-batch,generated-keys auto-retrieval for batch execution configurable>>.
** `ProxyDataSourceBuilder#retrieveGeneratedKeysForBatch`
***  batch execution for `Statement`: auto-retrieval is set to `false` to default
***  batch execution for `Prepared/Callable`: auto-retrieval is set to `true` to default