[[how-to-use]]
== How to use

`ProxyDataSource` implements `javax.sql.DataSource`, and works as an entry point for all interceptor logic.
You can directly instantiate `ProxyDataSource`, or use builder class `ProxyDataSourceBuilder` to build it. +
Once `ProxyDataSource` is setup, you can pass it as a datasource to your application.


[[creating-proxydatasource]]
=== Creating ProxyDataSource

`ProxyDataSourceBuilder` provides fluent API to construct `ProxyDataSource` instance.
Also, it provides builder methods to register built-in or custom listeners.

```java
DataSource dataSource =
    ProxyDataSourceBuilder.create(actualDataSource)  // pass original datasource
        .logQueryByCommons(INFO)    // logQueryBySlf4j(), logQueryByJUL(), logQueryToSysOut()
        .countQuery()               // enable query count metrics
        .logSlowQueryByCommons(10, TimeUnit.MINUTES)  // also by sl4j, jul, system out
        .proxyResultSet()           // enable proxying ResultSet
        .listener(myListener)       // register my custom listener
        .afterMethod(executionContext -> {    // register a custom listener with lambda
            ...
        })
        .build();
```

==== DriverManager and Connection Support

From instance of `java.sql.Connection`, you can create a proxy that is same as what `ProxyDataSource` returns.

```java
// obtain connection
Class.forName("org.hsqldb.jdbcDriver");
Connection realConnection = DriverManager.getConnection("jdbc:hsqldb:mem:aname");

ProxyConfig proxyConfig = ProxyConfig.Builder.create()
                             // configure more
                            .build();

JdbcProxyFactory jdbcProxyFactory = new JdkJdbcProxyFactory();
Connection proxyConnection = jdbcProxyFactory.createConnection(realConnection, proxyConfig);
...
```


==== Spring XML Configuration Support

Since `ProxyConfig` uses builder style instance creation, it is difficult to directly create
its bean in XML based spring config. `ProxyConfigSpringXmlSupport` class provides setters to
build `ProxyConfig` aiming to support bean creation in XML based spring config file.

.Sample XML config
```xml
<bean id="dataSource" primary="true" class="net.ttddyy.dsproxy.support.ProxyDataSource">
  <property name="dataSource" ref="actualDataSource"/>
  <property name="proxyConfig" ref="proxyConfig"/>
  <!--
    Alternatively, you can use SpEL to invoke create() method to get ProxyConfig bean.

    <property name="proxyConfig" value="#{proxyConfigSupport.create()}"/>
    -->
</bean>

<bean id="proxyConfig"
      factory-bean="proxyConfigSupport"
      factory-method="create"/>

<bean id="proxyConfigSupport" class="net.ttddyy.dsproxy.support.ProxyConfigSpringXmlSupport">
  <property name="dataSourceName" value="my-ds"/>
  <property name="queryListener" ref="queryListener"/>
  <property name="methodListener" ref="methodListener"/>
</bean>

<bean id="queryListener" class="net.ttddyy.dsproxy.listener.ChainListener">
  <property name="listeners">
    <list>
      <bean class="net.ttddyy.dsproxy.listener.logging.SystemOutQueryLoggingListener"/>
    </list>
  </property>
</bean>

<bean id="methodListener" class="net.ttddyy.dsproxy.listener.CompositeMethodListener">
  <property name="listeners">
    <list>
      <bean class="net.ttddyy.dsproxy.listener.TracingMethodListener"/>
    </list>
  </property>
</bean>
```


==== JNDI Support

```xml
<Resource name="jdbc/global/myProxy"
          auth="Container"
          type="net.ttddyy.dsproxy.support.ProxyDataSource"
          factory="net.ttddyy.dsproxy.support.jndi.ProxyDataSourceObjectFactory"
          description="ds"
          listeners="commons,count"
          proxyName="MyProxy"
          dataSource="[REFERENCE_TO_ACTUAL_DATASOURCE_RESOURCE]"  <!-- ex: java:jdbc/global/myDS -->
/>
```

datasource-proxy.jar and your choice of logging library(commons, slf4j, etc) needs to be accessible from container.


.JNDI Resource parameters
[cols="20,80"]
|===
| Parameter     | Description

| dataSource *(required)*   | Reference to actual datasource resource. ex: java:jdbc/global/myDS
| proxyName               | ProxyDataSource name
| logLevel                | Loglevel for commons-logging or slf4j. ex: DEBUG, INFO, etc.
| loggerName              | Name for logger. (since v1.3.1)
| listeners               | Fully qualified class name of QueryExecutionListener implementation class,or predefined values below. Can be comma delimited.
| queryTransformer        | Fully qualified class name of QueryTransformer implementation class.
| parameterTransformer    | Fully qualified class name of ParameterTransformer implementation class.
|===


.JNDI Resource "listeners" parameter
[cols="20,80"]
|===
| Parameter     | Description

| sysout        | Alias to net.ttddyy.dsproxy.listener.SystemOutQueryLoggingListener
| commons       | Alias to net.ttddyy.dsproxy.listener.CommonsQueryLoggingListener
| slf4j         | Alias to net.ttddyy.dsproxy.listener.SLF4JQueryLoggingListener
| count         | Alias to net.ttddyy.dsproxy.listener.DataSourceQueryCountListener
| x.y.z.MyQueryExecutionListener  | Fully qualified class name of QueryExecutionListener implementation
|===


.JNDI Resource "format" parameter
[cols="20,80"]
|===
| Parameter     | Description

| json          | Set logging output format as JSON
|===


See Tomcat configuration examples in {datasource-proxy-examples}[datasource-proxy-examples] project:

- {jndi-embedded-example}[with embedded tomcat]
- {jndi-external-example}[with external tomcat]

Also see `ProxyDataSourceObjectFactory` javadoc


=== Proxying ResultSet

By default, datasource-proxy does *NOT* proxy `ResultSet`. However, in some case, you want to return a proxied
`ResultSet` - for example, apply `MethodExecutionListener` on `ResultSet`.

To enable `ResultSet` proxy, `ProxyDataSourceBuilder` has `proxyResultSet()` method.

```java
builder
  // configure listeners
  .proxyResultSet()  // enable proxying result set
  .build();
```

In addition, the `proxyResultSet()` method takes `ResultSetProxyLogicFactory` to add some logic on
interacting with `ResultSet`. Default logic is no-op.


==== Repeatable Read ResultSet

`RepeatableReadResultSetProxyLogic` allows `ResultSet` to be consumed more than once.


```java
builder
  // configure listeners
  .repeatableReadResultSet()
//  .proxyResultSet(new RepeatableReadResultSetProxyLogicFactory())  // same as above
  .build();
```


[[listeners]]
=== Listeners

Currently, datasource-proxy provides two types of listener, `QueryExecutionListener` and `MethodExecutionListener`.


==== QueryExecutionListener

`QueryExecutionListener` is called when query execution methods are invoked.
(e.g.: `execute`, `executeBatch`, `executeQuery`, etc.)


.`QueryExecutionListener`:
```java
void beforeQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList);

void afterQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList);
```

`ExecutionInfo` contains contextual information about query execution(statement type, batch, connection id, etc),
and `QueryInfo` contains actual query string and parameters.

For `afterQuery` callback, `ExecutionInfo` contains additional information - result of query, time took to perform
query, and thrown exception.

Based on the type of query execution, number of queries and parameters changes.

|===
| Execution Type            | # of Query | # of Query Parameters

| Statement                 |          1 |  empty
| Statement (batch)         |          N |  empty
| Prepared Statement        |          1 |      1
| Prepared Statement (batch)|          1 |      N
| Callable Statement        |          1 |      1
| Callable Statement (batch)|          1 |      N
|===



==== MethodExecutionListener

`MethodExecutionListener` intercepts JDBC API calls on followings:

- `Connection`, `Statement`, `PreparedStatement`, `CallableStatement`: All methods
- `ResultSet`: All methods when result set proxy is enabled.
- `ProxyDataSource`: `getConnection()` method

