[[how-to-use]]
== How to use

`ProxyDataSource` implements `javax.sql.DataSource` and serves as the entry point for all interceptor logic.
You can directly instantiate `ProxyDataSource`, or use the `ProxyDataSourceBuilder` builder class to create it. +
Once `ProxyDataSource` is set up, you can pass it to your application as a datasource.


[[creating-proxydatasource]]
=== Creating ProxyDataSource

`ProxyDataSourceBuilder` provides a fluent API for constructing a `ProxyDataSource` instance.
It also provides builder methods for registering built-in and custom listeners.

[source,java]
----
DataSource dataSource =
    ProxyDataSourceBuilder.create(actualDataSource)  // pass the original datasource
        .logQueryByCommons(INFO)    // logQueryBySlf4j(), logQueryByJUL(), logQueryToSysOut()
        .loggingFilter(myFilter)    // filter which queries to log
        .countQuery()               // enable query count metrics
        .logSlowQueryByCommons(10, TimeUnit.MINUTES)  // also by slf4j, jul, system out
        .proxyResultSet()           // enable proxying ResultSet
        .listener(myListener)       // register a custom listener
        .afterMethod(executionContext -> {    // register a custom listener with lambda
            ...
        })
        .build();  // returns a ProxyDataSource instance
----

[[creating-a-proxied-datasource]]
==== Creating a proxied DataSource
Starting from datasource-proxy v1.10, the new `buildProxy()` method returns a pure `DataSource` proxy instance.

The difference between the `ProxyDataSource` returned by `build()` and the `DataSource` proxy returned by
`buildProxy()` is as follows:

* `ProxyDataSource` is a concrete implementation class.
  This class provides method callbacks only for the `getConnection` methods.
* The `DataSource` proxy is a pure proxy instance. It provides method callbacks for all methods.

[source,java]
----
DataSource dataSource =
    ProxyDataSourceBuilder.create(actualDataSource)  // pass the original datasource
        ...
        .buildProxy();  // returns DataSource
----

[[retrieving-the-original-jdbc-object]]
==== Retrieving the original JDBC object

All proxied JDBC objects implement the `ProxyJdbcObject` interface, which defines `getTarget()` to retrieve
the original JDBC object.

[source,java]
----
if (connection instanceof ProxyJdbcObject) {
    Connection original = (Connection) ((ProxyJdbcObject) connection).getTarget();
    ....
}
----


==== DriverManager and Connection Support

From an instance of `java.sql.Connection`, you can create a proxy that behaves the same way as the one
returned by `ProxyDataSource`.

```java
// obtain a connection
Class.forName("org.hsqldb.jdbcDriver");
Connection realConnection = DriverManager.getConnection("jdbc:hsqldb:mem:aname");

ProxyConfig proxyConfig = ProxyConfig.Builder.create()
                             // configure more
                            .build();

JdbcProxyFactory jdbcProxyFactory = new JdkJdbcProxyFactory();
Connection proxyConnection = jdbcProxyFactory.createConnection(realConnection, proxyConfig);
...
```


==== Spring XML Configuration Support

Because `ProxyConfig` is created using a builder-style API, it is not straightforward to create its bean in
an XML-based Spring configuration.
`ProxyConfigSpringXmlSupport` provides setters to build a `ProxyConfig` specifically for use in XML-based
Spring configuration files.

.Sample XML config
```xml
<bean id="dataSource" primary="true" class="net.ttddyy.dsproxy.support.ProxyDataSource">
  <property name="dataSource" ref="actualDataSource"/>
  <property name="proxyConfig" ref="proxyConfig"/>
  <!--
    Alternatively, you can use SpEL to invoke the create() method to get the ProxyConfig bean.

    <property name="proxyConfig" value="#{proxyConfigSupport.create()}"/>
    -->
</bean>

<bean id="proxyConfig"
      factory-bean="proxyConfigSupport"
      factory-method="create"/>

<bean id="proxyConfigSupport" class="net.ttddyy.dsproxy.support.ProxyConfigSpringXmlSupport">
  <property name="dataSourceName" value="my-ds"/>
  <property name="queryListener" ref="queryListener"/>
  <property name="methodListener" ref="methodListener"/>
</bean>

<bean id="queryListener" class="net.ttddyy.dsproxy.listener.ChainListener">
  <property name="listeners">
    <list>
      <bean class="net.ttddyy.dsproxy.listener.logging.SystemOutQueryLoggingListener"/>
    </list>
  </property>
</bean>

<bean id="methodListener" class="net.ttddyy.dsproxy.listener.CompositeMethodListener">
  <property name="listeners">
    <list>
      <bean class="net.ttddyy.dsproxy.listener.TracingMethodListener"/>
    </list>
  </property>
</bean>
```


==== JNDI Support

```xml
<Resource name="jdbc/global/myProxy"
          auth="Container"
          type="net.ttddyy.dsproxy.support.ProxyDataSource"
          factory="net.ttddyy.dsproxy.support.jndi.ProxyDataSourceObjectFactory"
          description="ds"
          listeners="commons,count"
          proxyName="MyProxy"
          dataSource="[REFERENCE_TO_ACTUAL_DATASOURCE_RESOURCE]"  <!-- ex: java:jdbc/global/myDS -->
/>
```

The datasource-proxy JAR and your chosen logging library (Commons, SLF4J, etc.) must be accessible from the
container.


.JNDI Resource parameters
[cols="20,80"]
|===
| Parameter     | Description

| dataSource *(required)*   | Reference to the actual datasource resource, for example: `java:jdbc/global/myDS`
| proxyName               | ProxyDataSource name
| logLevel                | Log level for Commons Logging or SLF4J, for example: `DEBUG`, `INFO`, etc.
| loggerName              | Logger name (since v1.3.1)
| listeners               | Fully qualified class name of a `QueryExecutionListener` implementation, or one of the predefined values below. Can be comma-delimited.
| queryTransformer        | Fully qualified class name of a `QueryTransformer` implementation.
| parameterTransformer    | Fully qualified class name of a `ParameterTransformer` implementation.
|===


.JNDI Resource "listeners" parameter
[cols="20,80"]
|===
| Parameter     | Description

| sysout        | Alias to `net.ttddyy.dsproxy.listener.logging.SystemOutQueryLoggingListener`
| commons       | Alias to `net.ttddyy.dsproxy.listener.logging.CommonsQueryLoggingListener`
| slf4j         | Alias to `net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener`
| count         | Alias to `net.ttddyy.dsproxy.listener.logging.DataSourceQueryCountListener`
| x.y.z.MyQueryExecutionListener  | Fully qualified class name of a `QueryExecutionListener` implementation
|===


.JNDI Resource "format" parameter
[cols="20,80"]
|===
| Parameter     | Description

| json          | Set the logging output format to JSON
|===


See Tomcat configuration examples in the {datasource-proxy-examples}[datasource-proxy-examples] project:

- {jndi-embedded-example}[with embedded Tomcat]
- {jndi-external-example}[with external Tomcat]

Also see the `ProxyDataSourceObjectFactory` Javadoc.


[[generated-keys]]
=== Generated Keys

[[auto-retrieve-generated-keys]]
==== Auto-retrieve generated keys

When 1) generated keys are available (for example, `Statement#RETURN_GENERATED_KEYS` is specified when a
statement is executed or when a prepared/callable statement is created) and 2) query execution methods
(`execute`, `executeUpdate`, `executeBatch`, etc.) are called, datasource-proxy automatically calls
`getGeneratedKeys()` and makes the returned `ResultSet` available via `ExecutionInfo#getGeneratedKeys()` in
`QueryExecutionListener`.

To enable auto-retrieval of generated keys:

```java
builder
  .autoRetrieveGeneratedKeys(...)
  .build();
```

NOTE: When `getGeneratedKeys()` is called: +
If a cached auto-retrieved generated key result set is still open, it is returned.
If there is no cached generated key result set, or the cached one has already been closed, datasource-proxy
performs the actual `getGeneratedKeys()` call on the underlying `Statement` object, caches the result, and then
returns it.

If you want to *always* retrieve generated keys without changing application code that may be executing a
query without `Statement#RETURN_GENERATED_KEYS`, see <<replace-invoking-method-and-parameters>>.
You can modify query executions to set `RETURN_GENERATED_KEYS`.

[[auto-retrieve-generated-keys-for-batch]]
===== For batch execution: `executeBatch()` and `executeLargeBatch()`

According to the JDBC specification, returning `getGeneratedKeys()` for `executeBatch()` and
`executeLargeBatch()` is implementation-specific:

[quote, from JDBC specification]
""
Note – It is implementation-defined as to whether
Statement.getGeneratedKeys will return generated values after invoking the
executeBatch or executeLargeBatch methods.
""


In datasource-proxy, whether to auto-retrieve generated keys for batch execution is configurable through
`ProxyDataSourceBuilder#retrieveGeneratedKeysForBatch()`.

```java
builder
  .autoRetrieveGeneratedKeys(...)
  .retrieveGeneratedKeysForBatch(false, true)  // first argument is for Statement,
                                               // second is for Prepared/Callable
  .build();
```

Default behavior for batch executions:

.Default behavior for auto retrieval of generated keys during batch execution
[cols="20,80"]
|===
| Type               | Auto Retrieval

| Statement          | Not retrieved
| Prepared/Callable  | Retrieved
|===



[[auto-close-generated-keys]]
==== Auto-close generated keys

When auto-close is enabled, the <<auto-retrieve-generated-keys, auto-retrieved generated keys>> are closed
after all `QueryExecutionListener#afterQuery()` callbacks have been processed.

This option is used with <<auto-retrieve-generated-keys, auto retrieve generated keys>> feature.

```java
builder
  .autoRetrieveGeneratedKeys(true)  // specify `true` or `false` to auto-close the `ResultSet`
  .build();
```


If you want to *reuse* the auto-retrieved generated-keys in upper layer, such as OR mapper or application, turn
off this auto-close feature; so that, cached generated-keys will be returned when `getGeneratedKeys()` is called.
Based on jdbc-driver implementation, calling `getGeneratedKeys()` might be limited to once.
When you decided to reuse generated-keys, you might need to support repeatable read on the `ResultSet`. see
<<proxying-generated-keys>> for how to support repeatable read on generated-keys.


NOTE: When `getGeneratedKeys()` is called, the returned `ResultSet` will NOT be closed by this feature since it is
not auto-retrieved generated-keys.

[[proxying-generated-keys]]
==== Proxying generated keys

Create a proxy for generated-keys' `ResultSet`.
This applies to both <<auto-retrieve-generated-keys, auto-retrieved generated-keys>> and result of
`getGeneratedKeys()`.

*Usecase*

You have a `QueryExecutionListener` that reads values from  generated-keys' `ResultSet`. Also, in upper layer, such as
ORM or application logic, it needs to use the same generated-keys' `ResultSet`.

Based on `ResultSet` implementation, reading values may be limited to only once; therefore, when
`QueryExecutionListener` reads values from generated-keys' `ResultSet` and upper layer tries to read values from it,
the `ResultSet` may not allow the repeated read.

To allow multiple reads, you can proxy the generated-keys' `ResultSet` with `RepeatableReadResultSetProxyLogic`.

```java
builder
   // specify proxy factory for generated-keys' result-set
  .autoRetrieveGeneratedKeys(false, new RepeatableReadResultSetProxyLogicFactory());
  // equivalent of above
  //   .autoRetrieveGeneratedKeysWithRepeatableReadProxy(false);
  .build();
```


=== Proxying ResultSet

By default, datasource-proxy does *NOT* proxy `ResultSet`. However, in some case, you want to return a proxied
`ResultSet` - for example, apply `MethodExecutionListener` on `ResultSet`.

To enable `ResultSet` proxy, `ProxyDataSourceBuilder` has `proxyResultSet()` method.

```java
builder
  // configure listeners
  .proxyResultSet()  // enable proxying result set
  .build();
```

In addition, the `proxyResultSet()` method takes `ResultSetProxyLogicFactory` to add some logic on
interacting with `ResultSet`. Default logic is no-op.

NOTE: This proxying does NOT apply to the `ResultSet` from `getGeneratedKeys()`. To proxy the result of
`getGeneratedKeys()`, see <<proxying-generated-keys>>.

[[repeatable-read-resultset]]
==== Repeatable read ResultSet

`RepeatableReadResultSetProxyLogic` allows `ResultSet` to be consumed more than once.


```java
builder
  // configure listeners
  .repeatableReadResultSet()
//  .proxyResultSet(new RepeatableReadResultSetProxyLogicFactory())  // same as above
  .build();
```

[[repeatable-read-resultset-with-cachedrowsetresultsetproxylogic]]
==== Repeatable read ResultSet with CachedRowSetResultSetProxyLogic

New result set proxy, `CachedRowSetResultSetProxyLogic` is introduced at version `1.4.7`.
`CachedRowSetResultSetProxyLogic` uses `javax.sql.rowset.CachedRowSet` as underlying implementation, which is a
sub-interface of `ResultSet` and provides cursor scrollability in disconnected fashion.  +
Default `CachedRowSet` implementation is `com.sun.rowset.CachedRowSetImpl` for oracle JDK (note for `com.sun` package),
which you can change via `RowSetFactory` (please see details on JDK documentation).

To use `CachedRowSetResultSetProxyLogic` for `ResultSet` proxy, simply supply its proxy-logic factory,
`CachedRowSetResultSetProxyLogicFactory`, to `ProxyDataSourceBuilder` when enabling result set proxy.


```java
builder
  // proxy for regular ResultSet
  .proxyResultSet(new RepeatableReadResultSetProxyLogicFactory())
   // proxy for generated-keys
  .autoRetrieveGeneratedKeys(false, new RepeatableReadResultSetProxyLogicFactory());
  .build();
```

[[using-a-custom-resultset-proxy]]
==== Using a custom ResultSet proxy

The `proxyResultSet` and `autoRetrieveGeneratedKeys` methods on the `ProxyDataSourceBuilder` can take a `ResultSetProxyLogicFactory` factory implementation. If you want to provide custom logic for handling the `ResultSet` object, you can provide a custom implementation by providing a custom factory implementation.

For example, https://github.com/jdbc-observations/datasource-proxy/pull/98/files[this code in the datasource-proxy pull request #98] provides a Spring's `SqlRowSet` based `ResultSet` proxy implementation to cover some shortcomings from the `com.sun.rowset.CachedRowSetImpl`.
