[[listeners]]
== Listeners

Currently, datasource-proxy provides the following listeners:

- `QueryExecutionListener`
- `MethodExecutionListener`
- `JdbcLifecycleEventListener`


=== QueryExecutionListener

`QueryExecutionListener` is called when query execution methods are invoked
(for example: `execute`, `executeBatch`, `executeQuery`, and so on).


.`QueryExecutionListener`:
```java
void beforeQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList);

void afterQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList);
```

`ExecutionInfo` contains contextual information about query execution (statement type, batch, connection ID,
and so on), and `QueryInfo` contains the actual query string and parameters.

For the `afterQuery` callback, `ExecutionInfo` contains additional information: the query result, the time it
took to execute the query, and any thrown exception.

The number of queries and parameters depends on the type of query execution.

|===
| Execution Type            | # of Query | # of Query Parameters

| Statement                 |          1 |  empty
| Statement (batch)         |          N |  empty
| Prepared Statement        |          1 |      1
| Prepared Statement (batch)|          1 |      N
| Callable Statement        |          1 |      1
| Callable Statement (batch)|          1 |      N
|===



=== MethodExecutionListener

`MethodExecutionListener` intercepts JDBC API calls for the following types:

- `Connection`, `Statement`, `PreparedStatement`, and `CallableStatement`: all methods
- `ResultSet`: all methods when the result set proxy is enabled
- `ProxyDataSource`: `getConnection()` method


[[replace-invoking-method-and-parameters]]
==== Replace the invoking method and parameters

In `MethodExecutionListener#beforeMethod()`, you can change the invoking method and its parameters on the
target JDBC object.

For example, in application code, it may call `Statement#execute(String)`. However, to leverage
<<generated-keys,generated-keys retrieval>>, you may want to call `Statement#execute(String, int)` instead
without changing application code.

To update or replace the method and parameters, set the new method or arguments via
`MethodExecutionContext#setMethod()` and `MethodExecutionContext#setMethodArgs()` inside
`MethodExecutionListener#beforeMethod()`.


For the above use case:

```java
private static final Method EXECUTE_METHOD = Statement.class.getMethod("execute", String.class);
private static final Method EXECUTE_WITH_INT_METHOD = Statement.class.getMethod("execute", String.class, int.class);

@Override
public void beforeMethod(MethodExecutionContext executionContext) {

  // replace "Statement#execute(sql)" with "Statement#execute(sql, RETURN_GENERATED_KEYS)"
  if (EXECUTE_METHOD.equals(executionContext.getMethod())) {

    Object[] originalArgs = executionContext.getMethodArgs();
    Object[] newArgs = new Object[]{originalArgs[0], Statement.RETURN_GENERATED_KEYS};

    executionContext.setMethod(EXECUTE_WITH_INT_METHOD);  // new method
    executionContext.setMethodArgs(newArgs);  // new method parameters
  }

}
```


[[jdbclifecycleeventlistener]]
=== JdbcLifecycleEventListener

The `JdbcLifecycleEventListener` interface defines before/after method callbacks for all JDBC interfaces that
datasource-proxy proxies (`DataSource`, `Connection`, `Statement`, `PreparedStatement`, `CallableStatement`,
and `ResultSet`). It also defines before/after callbacks for method invocations and query executions,
analogous to `MethodExecutionListener` and `QueryExecutionListener`.


To implement your listener, you can extend `JdbcLifecycleEventListenerAdapter`, which implements all
interface methods with no-op implementations and lets you selectively override the callbacks you care about.

```java
DataSource dataSource =
  ProxyDataSourceBuilder.create(actualDataSource)
    .listener(new JdbcLifecycleEventListenerAdapter() {
      @Override
      public void beforeGetConnection(MethodExecutionContext executionContext) {
        // implement the logic before DataSource#getConnection();
      }

      @Override
      public void afterRollback(MethodExecutionContext executionContext) {
        // implement the logic after Connection#rollback();
      }
    })
    .build();

```

[[jdbclifecycleeventlistener-overloaded-methods]]
==== Overloaded methods

Because JDBC API classes are hierarchical (for example, `PreparedStatement` extends `Statement`), some
methods are overloaded. For example, `PreparedStatement#execute` overloads `Statement#execute`, and
`PreparedStatement#setInt` and `CallableStatement#setInt` are both overloaded forms.

`JdbcLifecycleEventListener` callbacks are invoked by comparing the invoked method name.
Therefore, in this example, `[before|after]Execute` and `[before|after]setInt` are called.
If you need to know exactly which overload was invoked, check the invoked instance, method, or arguments to
identify the actual method that was called.

