[[listeners]]
== Listeners

Currently, datasource-proxy provides following listeners:

- `QueryExecutionListener`
- `MethodExecutionListener`
- `JdbcLifecycleEventListener`


=== QueryExecutionListener

`QueryExecutionListener` is called when query execution methods are invoked.
(e.g.: `execute`, `executeBatch`, `executeQuery`, etc.)


.`QueryExecutionListener`:
```java
void beforeQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList);

void afterQuery(ExecutionInfo execInfo, List<QueryInfo> queryInfoList);
```

`ExecutionInfo` contains contextual information about query execution(statement type, batch, connection id, etc),
and `QueryInfo` contains actual query string and parameters.

For `afterQuery` callback, `ExecutionInfo` contains additional information - result of query, time took to perform
query, and thrown exception.

Based on the type of query execution, number of queries and parameters changes.

|===
| Execution Type            | # of Query | # of Query Parameters

| Statement                 |          1 |  empty
| Statement (batch)         |          N |  empty
| Prepared Statement        |          1 |      1
| Prepared Statement (batch)|          1 |      N
| Callable Statement        |          1 |      1
| Callable Statement (batch)|          1 |      N
|===



=== MethodExecutionListener

`MethodExecutionListener` intercepts JDBC API calls on followings:

- `Connection`, `Statement`, `PreparedStatement`, `CallableStatement`: All methods
- `ResultSet`: All methods when result set proxy is enabled.
- `ProxyDataSource`: `getConnection()` method


[[replace-invoking-method-and-parameters]]
==== Replace invoking method and parameters

In `MethodExecutionListener#beforeMethod()`, you could change the invoking method and its parameters on target JDBC object.

For example, in application code, it calls `Statement#execute(String)`. However, in order to leverage
<<generated-keys,generated-keys retrieval>>, you may want to call `Statement#execute(String,int)` instead without
changing application code.

To update/replace method and parameters, you could set new method or parameters via `MethodExecutionContext#setMethod()`
 and `MethodExecutionContext#setMethodArgs()` in `MethodExecutionListener#beforeMethod()`.


For above example use case:

```java
private static final Method EXECUTE_METHOD = Statement.class.getMethod("execute", String.class);
private static final Method EXECUTE_WITH_INT_METHOD = Statement.class.getMethod("execute", String.class, int.class);

@Override
public void beforeMethod(MethodExecutionContext executionContext) {

  // replace "Statement#execute(sql)" to "Statement#execute(sql, RETURN_GENERATED_KEYS)"
  if(EXECUTE_METHOD.equals(executionContext.getMethod())) {

    Object[] orgArgs = executionContext.getMethodArgs();
    Object[] newArgs = new Object[]{orgArgs[0], Statement.RETURN_GENERATED_KEYS};

    executionContext.setMethod(EXECUTE_WITH_INT_METHOD);  // new method
    executionContext.setMethodArgs(newArgs);  // new method params
  }

}
```


[[jdbclifecycleeventlistener]]
=== JdbcLifecycleEventListener

`JdbcLifecycleEventListener` interface defines before/after method callbacks for all of JDBC interfaces that
datasource-proxy make proxies(`DataSource`, `Connection`, `Statement`, `PreparedStatement`, `CallableStatement`,
and `ResultSet`). Also, this interface defines before/after execution of all method invocations and query executions,
analogous to `MethodExecutionListener` and `QueryExecutionListener`.


To implement your listener, `JdbcLifecycleEventListenerAdapter` class, which implements all
interface methods with no-op, can be extended, and selectively overrides any callback methods you have interests.

```java
DataSource dataSource =
  ProxyDataSourceBuilder.create(actualDataSource)
    .listener(new JdbcLifecycleEventListenerAdapter() {
      @Override
      public void beforeGetConnection(MethodExecutionContext executionContext) {
        // impl for before DataSource#getConnection();
      }

      @Override
      public void afterRollback(MethodExecutionContext executionContext) {
        // impl for after Connection#rollback();
      }
    })
    .build();

```

[[jdbclifecycleeventlistener-overloaded-methods]]
==== Overloaded methods

Since JDBC API classes are hierarchical (e.g.: `PreparedStatement` extends `Statement`) some
of the methods are overloaded. For example, `PreparedStatement#execute` method is overloading `Statement#execute`. Another example is
`PreparedStatement#setInt` and `CallableStatement#setInt`.

`JdbcLifecycleEventListener` methods are called back by comparing the invoked method name.
Therefore, in this example, `[before|after]Execute` and `[before|after]setInt` will be called.
If you need to know exactly which of the method is called, you could check the invoked instance, method,
or passed arguments to diagnose the actual invoked method when it is overloaded.

